apiVersion: apps/v1
kind: Deployment
metadata:
  name: fragment
spec:
  template:
    spec:
      containers:
      - name: php
        env:
        - name: APP_ENV
          value: stg
        - name: ENJOY_ENVIRONMENT
          value: plng-stg